os: osx
osx_image: xcode10
language: swift
install: swift package update
script: swift test -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13
notifications:
  email: false
  slack:
    rooms:
      secure: BcZCk9muUFtew3KL6SxQgBNvUbWJcVAQBGuY0RB3E3wxg7Og7Irm9YtUEIMEp5/G8HRUokyaajjYAHeUoGQahbUgZXNvjpdQHUYB3mldSiUHK/5PsHxLTK74624x0hKkFf6QUTGBRMhtKDzJB93QKynQ6a3y1ppftiG/YlgXC4S2ZlZw2Z4lL3jzZtQRVhKTK3mSRFxwV3rYYiZClhYmCWB3c3SohBeD3rkPePGWQmhM0NLwY7RYGznvYPsAauox3USd5TXdHSothqEgPfKN4eF6ymp1EH8/NoJIfTokZoTG6+qxkR+lbEgGtzMAQthgLRhDEI7pWp/lISdF8yp1i8wxq8B7x1I6td4lwFL5PEsFr8oGTCj6lrMOdjVzHmrNXZ4rwG2kYvSDVVF6RoaI+4W+ONF9RiAwmr6mdRew6qMfONAWPFyjA3+RDOp7CcAgT0V2TmoYpr8s3z1evEsBmOX2qyNqimcqzrQ8gO7HnljZTREmBesy0ICNW1h6PwAifXrqCdyIQIgOSFcZ3vNneyUJB1qrLOkWRz+xJVYuJwLta9KjwZ0G1BYbFW/Gm5OcecLUvkPGuggUwQY2IsqelCOB/p4RhFCvekN9H0OHL1bHhNrVsZl3sny5r1U4vHnpI98Hd+b87whSwOgNM9YR64dDz40u0drxwO0cCmwf14k=
