os: osx
osx_image: xcode10
language: swift
install: swift package update
script: swift test -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13
notifications:
  email: false
  slack:
    rooms:
      secure: fGdVvet+KHyQNUROY1oNtlrfzRCNdq2MSljHF8FXZTqsLT/2BLC8x35zoaCz8TAHaWi5jeg10IXBRdTrsOSqnvGTpm7g+5xJNVkbzo3hDz/0ghtxB9pUzIybhLLJwPE0tdsCIdKdkiIf0YdPHeiliGkRtMDkvwzFNZLaaGow4QXEAr93n1mJSfN6qxn+hRdYzIO94L9yRfu1M7ReB2FVKoSpZEybMElKU6aKfpeNAq4MlIODXnlYeZ5HwpjsrHUuhXuhbAbcR0z9jX4/1wlwSXkNd+kobJyA3HK0pbZ3/pkFcjBi+AjxGoQGNA+w3hZ2zZQYlfaUA5PH0GfC+ew0j3poTItOY/2vnvBmAun4HYzjta/QECnz4snKpZ2qxnClrZj5ZlQ02wWYf6RXmIWekDTSpN4D+o+RIlGmfqTfIgA+3mIenz8iHp6qiwo8hF/2yhtptLANIUEXWx6IpQRqog/+suAczpy89DtDaQPfHToAD0VF3VylHqCgl/UXDp3wXO0C9cwi/sz8L0O1WRlTmwbGLzgyVBiv6D91EBODMTXOIyPlHgBfgwIlGBE5UqR1HGh5p2OpWH670rSMIc8BfRejeILLEvCN2JQFP2826g5AUDx2YxvYcI8fddDSib044wiPQlAKKEG3HdQT4Oxg7eHGfxqmIAXNq6FaWrBBuWE=
