matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      install:
        - SWIFT_BRANCH=swift-5.0.1-release
        - SWIFT_VERSION=swift-5.0.1-RELEASE
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
        - swift package update
      script:
        - swift test


    - os: osx
      osx_image: xcode10.2
      language: swift
      sudo: required
      install:
        - swift package update
        - sudo gem install xcpretty-travis-formatter

      script:
      - .bin/tests

notifications:
  email: false
  slack:
    rooms:
      secure: GP5NNLxlXm/MNsKDGrrNN1IGJ2pNpoQUdLilpoQkBPxZ7gR4kbc12j/WsNgtm6hRlDQ7N83ny8/aXrYXlwwzMvcnUZCLkZLnAVlQmrAC05J2yL14N2Rvn3TQejr9a/wl3df4XIXc7B83EWS1QTUimKOjg0GuEwhGcQuyLlAIj8xCBpjfN6t5cy9uQV0MRfFzTXBLUlShy8F7wONoaQ8mV21XQ6DTzD02Xb5wEbCxiP2JSDQlUSfgPT8YbuX4TgJPrdKyGCNxuWcfLpxaI5OK8eve4KhpxhCnsdra3nJtsw8RzmEDkmh6+d5ts4miVo7jnedsFxco95PYmeurCOBEdFHtvydclRmqetMmYBhILVrRNM9LdV/OOUzvsmZVSJ9TSqhZsiKaVUah5ZSiEEHw9zizNP3uBAmlhM5f+GAHa4c5X6ftzcNODfwuOL8KYgBcudI5kk/voZRovJjr24aw09BKqTjdXUheD76WAOtdfUorNi9JAiopRpV7tilL/jVUfpO3g5HSJvor52DI0YN2+ic+Wrx0MGE86dXDaKpfnld6vkXG8nxypMCkcVN2ZtOl6gLeKU6VidoJzFun+JTaROHf9gEGhse0QVXWYEYTFONbmpC2WbsUyyf0JQ0BrE8fKz6Xnmpv0R9fRgVNOjehw4CRPYKOvJV1gaJLDmks5ak=
