#if !canImport(ObjectiveC) && !os(watchOS)
import XCTest

extension ActionContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionContextTests = [
        ("testBasics", testBasics),
        ("testDefaultSender", testDefaultSender),
        ("testDescription", testDescription),
        ("testExplicitSender", testExplicitSender),
        ("testFlags", testFlags),
    ]
}

extension ActionIdentificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionIdentificationTests = [
        ("testAssociated", testAssociated),
        ("testAssociatedNotSet", testAssociatedNotSet),
        ("testBasics", testBasics),
        ("testFixed", testFixed),
    ]
}

extension ActionObserverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionObserverTests = [
        ("testBasics", testBasics),
        ("testNoDuplication", testNoDuplication),
    ]
}

extension ActionSerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionSerializationTests = [
        ("testArraySerialization", testArraySerialization),
        ("testContextSerialization", testContextSerialization),
        ("testNumberSerialization", testNumberSerialization),
        ("testStringSerialization", testStringSerialization),
    ]
}

extension ActionsNotificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionsNotificationTests = [
        ("testGlobalNotifications", testGlobalNotifications),
        ("testRegistrationForAnyAction", testRegistrationForAnyAction),
        ("testRegistrationForSpecificAction", testRegistrationForSpecificAction),
        ("testRegistrationSending", testRegistrationSending),
    ]
}

extension ActionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionsTests = [
        ("testArguments", testArguments),
        ("testCantGetIdentifierFromSender", testCantGetIdentifierFromSender),
        ("testCustomProvider", testCustomProvider),
        ("testCustomResponderChain", testCustomResponderChain),
        ("testDefaultAction", testDefaultAction),
        ("testGetIdentifierFromSender", testGetIdentifierFromSender),
        ("testPerform", testPerform),
        ("testPrefix", testPrefix),
        ("testSenderIsResponder", testSenderIsResponder),
        ("testSkipValidation", testSkipValidation),
        ("testUnregistered", testUnregistered),
        ("testValidate", testValidate),
        ("testValidateCantGetIdentifierFromSender", testValidateCantGetIdentifierFromSender),
        ("testValidateGettingIdentifierFromSender", testValidateGettingIdentifierFromSender),
    ]
}

extension DelegatedActionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DelegatedActionTests = [
        ("testAction1", testAction1),
        ("testAction2", testAction2),
        ("testDelegated", testDelegated),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ActionContextTests.__allTests__ActionContextTests),
        testCase(ActionIdentificationTests.__allTests__ActionIdentificationTests),
        testCase(ActionObserverTests.__allTests__ActionObserverTests),
        testCase(ActionSerializationTests.__allTests__ActionSerializationTests),
        testCase(ActionsNotificationTests.__allTests__ActionsNotificationTests),
        testCase(ActionsTests.__allTests__ActionsTests),
        testCase(DelegatedActionTests.__allTests__DelegatedActionTests),
    ]
}
#endif
